mysql:
  host: 127.0.0.1
  port: 3306
  db: blog
  user: root
  password: root
  log_level: dev
logger:
  level: info
  prefix: '[con]'
  director: log
  show-line: true
  log-in-console: true
system:
  host: "0.0.0.0"
  prot: 8080
  env: dev